# Generated by Django 3.2 on 2021-05-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100, verbose_name='Event')),
                ('description', models.TextField(verbose_name='Описание')),
                ('event_status', models.CharField(choices=[('potential', 'Потенциальный'), ('job', 'В работе'), ('completed', 'Завершен')], max_length=20, verbose_name='Статус мероприятия')),
                ('event_type', models.CharField(choices=[('installation', 'Монтаж'), ('report roller', 'Отчетный видеоролик'), ('interior photography', 'Интерьерная съемка'), ('survey', 'Съемка'), ('on-line translation', 'Онлайн трансляция'), ('filming and online broadcasting', 'Съемка и онлайн трансляция')], max_length=40, verbose_name='Тип мероприятия')),
                ('email', models.CharField(max_length=100, verbose_name='e-Mail заказчика')),
                ('date', models.DateField(blank=True, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('rang', models.CharField(max_length=50, verbose_name='Должность')),
            ],
        ),
    ]
