# Generated by Django 3.2 on 2021-05-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_task_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='budget',
            field=models.IntegerField(blank=True, default=0, verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='event',
            name='costs',
            field=models.IntegerField(blank=True, default=0, verbose_name='Расходы'),
        ),
        migrations.AddField(
            model_name='event',
            name='remnant',
            field=models.IntegerField(blank=True, default=0, verbose_name='Остаток'),
        ),
    ]
